### ISSUE TITLE
Would love the ability to "pin" the master viewcontroller

### ISSUE THREAD

**Issue by MattKiazyk** [bdbergeron/BDBSplitViewController#1]
so that both the master and detail are both visible on the same screen - the same as UISplitViewController.

**Comment by bdbergeron** [comment]
Working on it. Decided to implement a masterViewDisplayStyle and three states - normal, sticky, and drawer. Normal will act like the regular UISplitViewController, sticky will keep the master view visible no matter the orientation, and drawer will operate as shown in the demo graphic (as it does now). All styles will support showing and hiding using the showMasterView/hideMasterView methods.

Hope to have it posted later today. Ill bump the version when I do.

**Comment by bdbergeron** [comment]
Take a look at 1.1.0. Let me know if you have any issues with it.
