### ISSUE TITLE
Master view controller blank on initial presentation with storyboard

### ISSUE THREAD

**Issue by videege** [bdbergeron/BDBSplitViewController#3]
I've got a strange issue - I've set up a master-detail iPad application (with storyboard) and changed it so that my SplitViewController class is now a subclass of BDBSplitViewController; my detail view implements BDBDetailViewController.

When I debug the app, the first time the master view is opened (in any orientation), all I see is an odd border where the master view should be (it is transparent and I can see the detail view underneath).  

![screen shot 2013-12-05 at 9 56 25 pm](https://f.cloud.github.com/assets/718764/1689926/03629a2a-5e33-11e3-8719-468f1bc92e0b.png)

When I tap off, the messed up view closes, and if I try to open it again, the view then reappears and is rendered correctly.

![screen shot 2013-12-05 at 9 58 25 pm](https://f.cloud.github.com/assets/718764/1689930/12c6f7ea-5e33-11e3-9613-f7c145cd2184.png)

Any ideas?  Is there some configuration necessary when using storyboards that I'm not aware of?

**Comment by bdbergeron** [comment]
I have not done any sort of testing with storyboards just because I never use storyboards in my workflow. I will try my best to debug this issue tomorrow or over the weekend.

**Comment by amcastror** [comment]
Any luck here?

**Comment by bdbergeron** [comment]
Version 1.3.0 (afa8fd2) now has support for Storyboards. Please take a look at the new Storyboard Demo for insight into how you can get your project working with BDBSplitViewController.
