### ISSUE TITLE
Sticky master view gets black while rotating

### ISSUE THREAD

**Issue by guilhermearaujo** [bdbergeron/BDBSplitViewController#4]
I set my master view to be sticky and always show, however when I change the orientation, the view disappears for an instant and gets black, and then it shows again.

It looks like the view fades out/slides to the left when I switch to portrait orientation, and slides back in when I rotate to landscape.

I am using a storyboard and set:

``` objective-c
- (void)viewDidLoad
{
  [super viewDidLoad];
  // Do any additional setup after loading the view.
  [self setMasterViewDisplayStyle:BDBMasterViewDisplayStyleSticky];
  [self showMasterViewControllerAnimated:NO completion:nil];
}
```

**Comment by bdbergeron** [comment]
This is a noted issue that I'm currently working on. I also have yet to do any testing with Storyboard-based implementations, but I will in the upcoming week. Thanks for the heads-up.

**Comment by bdbergeron** [comment]
Version 1.3.0 (afa8fd2) has better support for Storyboards. If you could take a look at that and let me know if it resolves your issue, I'd greatly appreciate it. Thanks!
